### PR TITLE
switch from jacoco to cobertura + new tests + travis caches

### PR DESCRIPTION
**Pull request by storozhukBM**

### CODE REVIEW

**Comment by storozhukBM** [comment]
Hmm it seems that coveralls show totally different numbers then IDEA. I should work on it more.

**Comment by storozhukBM** [comment]
At least this numbers are similar to IDEA coverage report 🙈

**Comment by storozhukBM** [comment]
I've switched jacoco to cobertura because it is able to handle tests that are using code instrumentation like PowerMock tests.

**Comment by RobWin** [comment]
Does it work with coveralls?

**Comment by storozhukBM** [comment]
Yes coverals check passed. Results [here](https://coveralls.io/builds/9216210)

**Pull request merged**
