### PR TITLE
Fix for race conditions if two threads increase the max error counter…

### PR DESCRIPTION
**Pull request by RobWin**
… at the same time.

### CODE REVIEW

**Comment by RobWin** [comment]
Hi @jburell,

I think, the RetryContext should not be used by multiple threads.
Retry is different to CircuitBreaker and RateLimiter in that case.

But anyway thank you for fixing this issue.

**Comment by RobWin** [comment]
Btw, if you like javaslang-circuitbreaker, we would love to get your GitHub star :)

**Comment by jburell** [comment]
@RobWin While I agree that the behavior is not thread safe, and that I don't need it for my use case, what is the purpose of the AtomicInteger?

**Comment by RobWin** [comment]
Hi, there is no purpose. I will fix this. I think this was introduces in a PR and I did not noticed that change.

**Comment by RobWin** [comment]
Thx for your start

**Pull request merged**
